### ISSUE TITLE
Finish WIP features

### ISSUE THREAD

**Issue by DarkoKukovec** [webpack-contrib/webpack-canary#31]
There are some features in the `add-additional-example-sources` branch that should be finished and merged to master:
* [x] Add verbose flag to squawk (e5522a9237b70dfb772fd967e15e1be072bedbfc) - #39
* [x] Support missing readme (e32693cd171f98fe8a7c7ae1b9f1640c4f0b3133) - #32
* [x] Add timing output and check for extract plugin example (f5d1390d18bc4c1b719c62123edc22a24f8d18d9) - #40
* [x] Update readme (92f78baba3ffee3ec2e3e789b4dca1db4fb67fc3) - #33
* [x] Support yarn warnings in stderr (f1ca52ff3e7c40d4874e4a52f0682a1f7331a8a2) - #43 

Commits covered by other issues:
* [x] Use yarn over npm for faster installs (f8bf6d31b98c5accf0ba36ec7d64d59677f8c486) - #21 
* [x] Reset package.json file after run (f898a12ab50654b153aa3f4664d383942d2a37b0) - #22 
* [x] Correct direct webpack call command (6382caf2f07364a87516a6469c8481fbe44875cf) - #22
